export const LOGOUT ='LOGOUT'
export const LOGIN_SUCCESS = 'LOGIN'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const FETCH_BUGS_REQUEST = 'FETCH_BUGS_REQUEST';
export const FETCH_BUGS_SUCCESS = 'FETCH_BUGS_SUCCESS';
export const FETCH_BUGS_FAILURE = 'FETCH_BUGS_FAILURE';